---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/component: database
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: redis
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: redis
        app.kubernetes.io/component: database
    spec:
      automountServiceAccountToken: false
      containers:
      - name: redis
        image: redis:latest
        ports:
        - name: redis
          containerPort: 6379
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
