---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: syncthing
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/part-of: components
  name: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: syncthing
      app.kubernetes.io/name: syncthing
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: syncthing
        app.kubernetes.io/name: syncthing
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: syncthing
        image: syncthing/syncthing:latest
        ports:
        - name: http
          containerPort: 8384
        - name: discovery
          containerPort: 21027
          protocol: UDP
        - name: syncthing
          containerPort: 22000
        resources:
          limits:
            cpu: 3000m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 128Mi
        volumeMounts:
        - name: data
          mountPath: /var/syncthing
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: syncthing-relay
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/part-of: components
  name: syncthing-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: syncthing-relay
      app.kubernetes.io/name: syncthing
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: syncthing-relay
        app.kubernetes.io/name: syncthing
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: syncthing-relay
        image: syncthing/relaysrv:latest
        args:
        - -global-rate=2000000
        - -provided-by='0x148 <https://0x148.com>'
        ports:
        - name: relaysrv
          containerPort: 22067
        - name: relaysrv-status
          containerPort: 22070
        resources:
          limits:
            cpu: 300m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - name: data
          mountPath: /var/strelaysrv
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: data
        emptyDir: {}
