---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/part-of: cluster
  name: cert-manager-cainjector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: cert-manager
      app.kubernetes.io/name: cainjector
      app.kubernetes.io/part-of: cluster
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cert-manager
        app.kubernetes.io/name: cainjector
        app.kubernetes.io/part-of: cluster
    spec:
      automountServiceAccountToken: true
      containers:
      - name: cainjector
        image: cert-manager/cainjector:latest
        args:
        - --leader-election-namespace=$(POD_NAMESPACE)
        - --v=2
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
          requests:
            cpu: 50m
            memory: 16Mi
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cert-manager-cainjector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: cluster
  name: cert-manager-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: cert-manager
      app.kubernetes.io/name: controller
      app.kubernetes.io/part-of: cluster
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9402'
      labels:
        app.kubernetes.io/component: cert-manager
        app.kubernetes.io/name: controller
        app.kubernetes.io/part-of: cluster
    spec:
      automountServiceAccountToken: true
      containers:
      - name: controller
        image: cert-manager/controller:latest
        args:
        - --cluster-resource-namespace=$(POD_NAMESPACE)
        - --leader-election-namespace=$(POD_NAMESPACE)
        - --v=2
        ports:
        - name: prometheus
          containerPort: 9402
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
          requests:
            cpu: 50m
            memory: 16Mi
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cert-manager-controller
