---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: cluster
  name: cert-manager
spec:
  ports:
  - name: prometheus
    port: 9402
    targetPort: prometheus
  selector:
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: cluster
  type: ClusterIP
