---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: localai
    app.kubernetes.io/name: localai
    app.kubernetes.io/part-of: services
  name: localai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: localai
      app.kubernetes.io/name: localai
      app.kubernetes.io/part-of: services
  template:
    metadata:
      labels:
        app.kubernetes.io/component: localai
        app.kubernetes.io/name: localai
        app.kubernetes.io/part-of: services
    spec:
      automountServiceAccountToken: false
      containers:
      - name: localai
        image: localai/localai:latest
        command:
        - /build/local-ai
        - run
        env:
        - name: LOCALAI_AUTOLOAD_GALLERIES
          value: 'true'
        - name: LOCALAI_DISABLE_WEBUI
          value: 'true'
        - name: LOCALAI_GALLERIES
          value: |-
            [
              {
                "name": "progamesigner-model-gallery",
                "url": "github:progamesigner/localai-model-gallery/index.yaml@main"
              },
              {
                "name":"localai",
                "url":"github:mudler/LocalAI/gallery/index.yaml@master"
              }
            ]
        - name: LOCALAI_P2P
          value: 'true'
        - name: LOCALAI_PARALLEL_REQUESTS
          value: 'true'
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: 4000m
            memory: 16Gi
          requests:
            cpu: 300m
            memory: 128Mi
        volumeMounts:
        - name: data
          mountPath: /build/models
      serviceAccountName: default
      volumes:
      - name: data
        emptyDir: {}
