---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: cloudflare-tunnel
    app.kubernetes.io/name: cloudflare
    app.kubernetes.io/part-of: applications
  name: cloudflare-tunnel
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: cloudflare-tunnel
      app.kubernetes.io/name: cloudflare
      app.kubernetes.io/part-of: applications
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cloudflare-tunnel
        app.kubernetes.io/name: cloudflare
        app.kubernetes.io/part-of: applications
    spec:
      automountServiceAccountToken: false
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - run
        env:
        - name: NO_AUTOUPDATE
          value: 'true'
        - name: TUNNEL_METRICS
          value: 0.0.0.0:2000
        envFrom:
        - secretRef:
            name: cloudflare
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /ready
            port: 2000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: default
