---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: home-assistant
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/part-of: components
  name: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: home-assistant
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: home-assistant
        app.kubernetes.io/name: home-assistant
        app.kubernetes.io/part-of: components
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload.kubernetes.progamesigner.dev/controller
                operator: Exists
      automountServiceAccountToken: false
      containers:
      - name: home-assistant
        image: home-assistant/home-assistant:latest
        env:
        - name: DB_URL
          value: postgresql://default:password@postgresql.default.svc.cluster.local/home-assistant
        - name: TZ
          value: UTC
        ports:
        - name: rtsp
          containerPort: 554
        - name: upnp
          containerPort: 1900
          protocol: UDP
        - name: mdns
          containerPort: 5353
          protocol: UDP
        - name: http
          containerPort: 8123
        - name: homekit
          containerPort: 21063
        - name: homekit-flow
          containerPort: 21064
        - name: upnp-40000
          containerPort: 40000
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: data
          mountPath: /config
        - name: dbus
          mountPath: /run/dbus
          readOnly: true
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: home-assistant
      - name: dbus
        hostPath:
          path: /run/dbus
