---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: home-assistant
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/part-of: components
  name: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: home-assistant
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/part-of: components
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "cluster",
              "namespace": "kube-system"
            },
            {
              "name": "local",
              "namespace": "kube-system",
              "mac": "7A:22:25:01:04:09"
            }
          ]
      labels:
        app.kubernetes.io/component: home-assistant
        app.kubernetes.io/name: home-assistant
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: home-assistant
        image: home-assistant/home-assistant:latest
        env:
        - name: DB_URL
          value: postgresql://default:password@postgresql.default.svc.cluster.local/home-assistant
        - name: TZ
          value: UTC
        ports:
        - name: dhcp-server
          containerPort: 67
          protocol: UDP
        - name: dhcp-client
          containerPort: 68
          protocol: UDP
        - name: rtsp
          containerPort: 554
        - name: rtsp-udp
          containerPort: 554
          protocol: UDP
        - name: upnp
          containerPort: 1900
          protocol: UDP
        - name: mdns
          containerPort: 5353
          protocol: UDP
        - name: http
          containerPort: 8123
        - name: homekit
          containerPort: 21063
        - name: homekit-flow
          containerPort: 21064
        - name: upnp-40000
          containerPort: 40000
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: data
          mountPath: /config
        - name: dbus
          mountPath: /run/dbus
          readOnly: true
      serviceAccountName: default
      volumes:
      - name: data
        emptyDir: {}
      - name: dbus
        hostPath:
          path: /run/dbus
