---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: clamav
    app.kubernetes.io/name: clamav
    app.kubernetes.io/part-of: components
  name: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: clamav
      app.kubernetes.io/name: clamav
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: clamav
        app.kubernetes.io/name: clamav
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: true
      containers:
      - name: clamav
        image: clamav/clamav:latest
        ports:
        - name: clamd
          containerPort: 3310
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 64Mi
      enableServiceLinks: false
      serviceAccountName: default
