nameReference:
- kind: ConfigMap
  fieldSpecs:
  - kind: Deployment
    path: spec/template/metadata/annotations/nginx.org\/nginx-configmaps

- kind: Secret
  fieldSpecs:
  - kind: Issuer
    path: spec/acme/solvers/dns01/cloudflare/apiTokenSecretRef/name
