---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: adguard-home/adguard-home
  newName: adguard/adguardhome
  newTag: v0.107.74
- name: apprise/apprise
  newName: caronc/apprise
  newTag: 1.1.8
- name: bifrost/bifrost
  newName: maximhq/bifrost
  newTag: v1.5.0-prerelease3
- name: clamav/clamav
  newName: clamav/clamav
  newTag: 1.5.1
- name: coder/coder
  newName: ghcr.io/coder/coder
  newTag: v2.11.3
- name: gloomhaven/client
  newName: gloomhavensecretariat/ghs
  newTag: v0.144.7
- name: gloomhaven/server
  newName: gloomhavensecretariat/ghs-server-postgresql
  newTag: v0.144.0
- name: home-assistant/home-assistant
  newName: ghcr.io/home-assistant/home-assistant
  newTag: 2026.4.3
- name: mongodb/compass
  newName: haohanyang/compass-web
  newTag: 0.4.0-beta.1
- name: network/cloudflare-warp
  newName: amirdaaee/cloudflare-warp
  newTag: 2023.10.120-1
- name: network/cloudflared
  newName: cloudflare/cloudflared
  newTag: 2026.3.0
- name: network/haproxy
  newName: haproxy
  newTag: 3.0.2-alpine
- name: network/tailscale
  newName: ghcr.io/tailscale/tailscale
  newTag: v1.94.2
- name: network/wireguard
  newName: ghcr.io/jordanpotter/docker-wireguard
  newTag: '2025-05-20'
- name: obsidian/obsidian
  newName: ghcr.io/belphemur/obsidian-headless-sync-docker
  newTag: 0.0.8
- name: pgadmin/pgadmin
  newName: dpage/pgadmin4
  newTag: '9.13'
- name: phpmyadmin/phpmyadmin
  newName: phpmyadmin
  newTag: 5.2.1
- name: redis/insight
  newName: redis/redisinsight
  newTag: '2.70'
- name: rsshub/rsshub
  newName: diygod/rsshub
  newTag: '2026-04-19'
- name: seafile/backend
  newName: seafileltd/seafile-pro-mc
  newTag: 13.0-latest
- name: seafile/frontend
  newName: seafileltd/seafile-pro-mc
  newTag: 13.0-latest
- name: seafile/metadata
  newName: seafileltd/seafile-md-server
  newTag: 13.0-latest
- name: seafile/notification
  newName: seafileltd/notification-server
  newTag: 13.0-latest
- name: seafile/seadoc
  newName: seafileltd/sdoc-server
  newTag: 2.0-latest
- name: seafile/thumbnail
  newName: seafileltd/thumbnail-server
  newTag: 13.0-latest
- name: syncthing/relaysrv
  newName: syncthing/relaysrv
  newTag: 2.0.3
- name: syncthing/syncthing
  newName: syncthing/syncthing
  newTag: 2.0.3
- name: unifi/network
  newName: lscr.io/linuxserver/unifi-network-application
  newTag: 10.1.89-ls124
- name: vscode/server
  newName: ghcr.io/progamesigner/vscode-server
  newTag: 20230422-jammy
- name: windmill/windmill-extra
  newName: ghcr.io/windmill-labs/windmill-extra
  newTag: 1.687.0
- name: windmill/windmill-server
  newName: ghcr.io/windmill-labs/windmill
  newTag: 1.688.0
- name: windmill/windmill-worker
  newName: ghcr.io/windmill-labs/windmill
  newTag: 1.688.0
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: browserless
    spec:
      replicas: 2
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ceph-radosgw
    spec:
      replicas: 2
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: windmill-worker
    spec:
      replicas: 4
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: windmill-browser-worker
    spec:
      replicas: 2
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: windmill-native-worker
    spec:
      replicas: 0
resources:
- components
- kubernetes
- services
