
vouch:
  logLevel: info

  domains:
  - progamesigner.com

  whiteList:
  - yangzihhao@gmail.com

  jwt:
    secret: \3twNrT:V5j}[\#gK]~-T8VJ%?zA#txqNVs+\W4U,ap*
    issuer: PGS
    maxAge: 180
    compress: true

  cookie:
    name: PGS_AUTH_TOKEN
    secure: true
    httpOnly: true
    maxAge: 180

  session:
    name: PGS_AUTH_SESSION
    key: EZ#3{x8~O[C%y,u:o$EdC(vTke>B~VJU,^EV++78C.L_

oauth:
  provider: google
  client_id: 194097666740-3kngbbeetbr6gki6au883hdiavabskoc.apps.googleusercontent.com
  client_secret: AUwnD6Z_wwBWcJwPUVNs7BLP
  callback_urls:
  - https://auth.progamesigner.com/auth
