---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
  name: dify-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/name: dify
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/name: dify
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: migrator
        image: dify/api:latest
        command:
        - sh
        - -c
        - |
          set -ex;

          flask db upgrade
        envFrom:
        - configMapRef:
            name: dify
        - secretRef:
            name: dify
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 64Mi
      containers:
      - name: dify-api
        image: dify/api:latest
        env:
        - name: APP_WEB_URL
          value: ''
        - name: CONSOLE_API_URL
          value: ''
        - name: CONSOLE_WEB_URL
          value: ''
        - name: EDITION
          value: SELF_HOSTED
        - name: FORWARDED_ALLOW_IPS
          value: '*'
        - name: MODE
          value: api
        - name: SERVICE_API_URL
          value: ''
        envFrom:
        - configMapRef:
            name: dify
        - secretRef:
            name: dify
        ports:
        - name: http
          containerPort: 5001
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
  name: dify-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/name: dify
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
        app.kubernetes.io/name: dify
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dify-worker
        image: dify/worker:latest
        env:
        - name: APP_WEB_URL
          value: ''
        - name: CONSOLE_API_URL
          value: ''
        - name: CONSOLE_WEB_URL
          value: ''
        - name: EDITION
          value: SELF_HOSTED
        - name: MODE
          value: worker
        - name: SERVICE_API_URL
          value: ''
        envFrom:
        - configMapRef:
            name: dify
        - secretRef:
            name: dify
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
  name: dify-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      app.kubernetes.io/name: dify
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
        app.kubernetes.io/name: dify
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dify-web
        image: dify/web:latest
        env:
        - name: APP_API_URL
          value: ''
        - name: CONSOLE_API_URL
          value: ''
        - name: EDITION
          value: SELF_HOSTED
        ports:
        - name: http
          containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: nginx
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
  name: dify-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: nginx
      app.kubernetes.io/name: dify
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: nginx
        app.kubernetes.io/name: dify
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dify-nginx
        image: dify/nginx:latest
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
        volumeMounts:
        - name: files
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: files
          mountPath: /etc/nginx/proxy.conf
          subPath: proxy.conf
      serviceAccountName: default
      volumes:
      - name: files
        configMap:
          name: dify-nginx
