---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
  name: dify-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/name: dify
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/name: dify
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dify-api
        image: dify/api:latest
        env:
        - name: DB_DATABASE
          value: dify
        - name: GUNICORN_TIMEOUT
          value: '360'
        - name: INNER_API_KEY_FOR_PLUGIN
          valueFrom:
            secretKeyRef:
              name: dify
              key: PLUGIN_DAEMON_API_KEY
        - name: MODE
          value: api
        - name: PLUGIN_DAEMON_KEY
          valueFrom:
            secretKeyRef:
              name: dify
              key: PLUGIN_DAEMON_SERVER_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: dify
              key: API_SECRET_KEY
        - name: SERVER_WORKER_AMOUNT
          value: '2'
        envFrom:
        - configMapRef:
            name: dify
        - secretRef:
            name: dify
        ports:
        - name: http
          containerPort: 5001
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 256Mi
      enableServiceLinks: false
      serviceAccountName: default
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: migration
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
  name: dify-migration
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: migration
        app.kubernetes.io/name: dify
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dify-migration
        image: dify/migration:latest
        env:
        - name: DB_DATABASE
          value: dify
        - name: MIGRATION_ENABLED
          value: 'true'
        - name: MODE
          value: migration
        envFrom:
        - configMapRef:
            name: dify
        - secretRef:
            name: dify
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 256Mi
      enableServiceLinks: false
      restartPolicy: Never
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: plugin-daemon
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
  name: dify-plugin-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: plugin-daemon
      app.kubernetes.io/name: dify
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: plugin-daemon
        app.kubernetes.io/name: dify
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dify-plugin-daemon
        image: dify/plugin-daemon:latest
        env:
        - name: DB_DATABASE
          value: dify-plugins
        - name: DIFY_INNER_API_URL
          value: http://dify-api.default.svc.cluster.local:5001
        - name: DIFY_INNER_API_KEY
          valueFrom:
            secretKeyRef:
              name: dify
              key: PLUGIN_DAEMON_API_KEY
        - name: FORCE_VERIFYING_SIGNATURE
          value: 'true'
        - name: PLUGIN_REMOTE_INSTALLING_ENABLED
          value: 'true'
        - name: PLUGIN_REMOTE_INSTALLING_HOST
          value: 0.0.0.0
        - name: PLUGIN_REMOTE_INSTALLING_PORT
          valueFrom:
            secretKeyRef:
              name: dify
              key: PLUGIN_REMOTE_INSTALL_PORT
        - name: PLUGIN_STORAGE_TYPE
          valueFrom:
            configMapKeyRef:
              name: dify
              key: PLUGIN_STORAGE_TYPE
        - name: PLUGIN_WORKING_PATH
          value: /app/storage/cwd
        - name: SERVER_PORT
          value: '5002'
        - name: SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: dify
              key: PLUGIN_DAEMON_SERVER_KEY
        envFrom:
        - configMapRef:
            name: dify
        - secretRef:
            name: dify
        ports:
        - name: http
          containerPort: 5002
        - name: remote-plugins
          containerPort: 5003
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - name: data
          mountPath: /app/storage
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: sandbox
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
  name: dify-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: sandbox
      app.kubernetes.io/name: dify
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: sandbox
        app.kubernetes.io/name: dify
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dify-sandbox
        image: dify/sandbox:latest
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: dify
              key: CODE_EXECUTION_API_KEY
        - name: ENABLE_NETWORK
          value: 'true'
        - name: ENABLE_PRELOAD
          value: 'true'
        - name: HTTP_PROXY
          valueFrom:
            secretKeyRef:
              name: dify
              key: SSRF_PROXY_HTTP_URL
        - name: HTTPS_PROXY
          valueFrom:
            secretKeyRef:
              name: dify
              key: SSRF_PROXY_HTTPS_URL
        - name: WORKER_TIMEOUT
          value: '60'
        ports:
        - name: http
          containerPort: 8194
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: conf
          mountPath: /dependencies/python-requirements.txt
          subPath: python-requirements.txt
          readOnly: true
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: conf
        configMap:
          name: dify-sandbox
          items:
          - key: python-requirements.txt
            path: python-requirements.txt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
  name: dify-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: scheduler
      app.kubernetes.io/name: dify
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: scheduler
        app.kubernetes.io/name: dify
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dify-scheduler
        image: dify/scheduler:latest
        env:
        - name: CELERY_WORKER_AMOUNT
          value: '1'
        - name: DB_DATABASE
          value: dify
        - name: INNER_API_KEY_FOR_PLUGIN
          valueFrom:
            secretKeyRef:
              name: dify
              key: PLUGIN_DAEMON_API_KEY
        - name: MODE
          value: beat
        - name: PLUGIN_DAEMON_KEY
          valueFrom:
            secretKeyRef:
              name: dify
              key: PLUGIN_DAEMON_SERVER_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: dify
              key: API_SECRET_KEY
        envFrom:
        - configMapRef:
            name: dify
        - secretRef:
            name: dify
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      enableServiceLinks: false
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: ssrf-proxy
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
  name: dify-ssrf-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ssrf-proxy
      app.kubernetes.io/name: dify
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ssrf-proxy
        app.kubernetes.io/name: dify
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dify-ssrf-proxy
        image: dify/ssrf-proxy:latest
        command:
        - sh
        - -c
        - |
          cp /docker-entrypoint-mount.sh /docker-entrypoint.sh && \
          chmod +x /docker-entrypoint.sh && \
          /docker-entrypoint.sh
        env:
        - name: COREDUMP_DIR
          value: /var/spool/squid
        - name: HTTP_PORT
          value: '3128'
        - name: REVERSE_PROXY_PORT
          value: '8194'
        - name: SANDBOX_HOST
          value: dify-sandbox.default.svc.cluster.local
        - name: SANDBOX_PORT
          value: '8194'
        ports:
        - name: proxy
          containerPort: 3128
        - name: reverse-proxy
          containerPort: 8194
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: conf
          mountPath: /docker-entrypoint-mount.sh
          subPath: docker-entrypoint.sh
          readOnly: true
        - name: conf
          mountPath: /etc/squid/conf.d/default.conf
          subPath: squid.conf
          readOnly: true
        - name: conf
          mountPath: /etc/squid/squid.conf.template
          subPath: squid.conf.template
          readOnly: true
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: conf
        configMap:
          name: dify-ssrf-proxy
          items:
          - key: docker-entrypoint.sh
            path: docker-entrypoint.sh
          - key: squid.conf
            path: squid.conf
          - key: squid.conf.template
            path: squid.conf.template
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
  name: dify-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      app.kubernetes.io/name: dify
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
        app.kubernetes.io/name: dify
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dify-web
        image: dify/web:latest
        env:
        - name: APP_API_URL
          value: ''
        - name: CONSOLE_API_URL
          value: ''
        - name: MARKETPLACE_API_URL
          value: https://marketplace.dify.ai
        - name: MARKETPLACE_URL
          value: https://marketplace.dify.ai
        - name: PM2_INSTANCES
          value: '1'
        ports:
        - name: http
          containerPort: 3000
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 128Mi
      enableServiceLinks: false
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
  name: dify-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/name: dify
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
        app.kubernetes.io/name: dify
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dify-worker
        image: dify/worker:latest
        env:
        - name: CELERY_WORKER_AMOUNT
          value: '2'
        - name: DB_DATABASE
          value: dify
        - name: INNER_API_KEY_FOR_PLUGIN
          valueFrom:
            secretKeyRef:
              name: dify
              key: PLUGIN_DAEMON_API_KEY
        - name: MODE
          value: worker
        - name: PLUGIN_DAEMON_KEY
          valueFrom:
            secretKeyRef:
              name: dify
              key: PLUGIN_DAEMON_SERVER_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: dify
              key: API_SECRET_KEY
        envFrom:
        - configMapRef:
            name: dify
        - secretRef:
            name: dify
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      enableServiceLinks: false
      serviceAccountName: default
