---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dify-plugin-daemon
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: ceph-cephfs
