---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: browserless
    app.kubernetes.io/name: browserless
    app.kubernetes.io/part-of: services
  name: browserless
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: browserless
      app.kubernetes.io/name: browserless
      app.kubernetes.io/part-of: services
  template:
    metadata:
      labels:
        app.kubernetes.io/component: browserless
        app.kubernetes.io/name: browserless
        app.kubernetes.io/part-of: services
    spec:
      automountServiceAccountToken: false
      containers:
      - name: browserless
        image: browserless/browserless:latest
        envFrom:
        - secretRef:
            name: browserless
        ports:
        - name: http
          containerPort: 3000
        resources:
          limits:
            cpu: 1500m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 256Mi
      enableServiceLinks: false
      serviceAccountName: default
