---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: radosgw
    app.kubernetes.io/name: ceph
    app.kubernetes.io/part-of: services
  name: ceph-radosgw
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: radosgw
      app.kubernetes.io/name: ceph
      app.kubernetes.io/part-of: services
  template:
    metadata:
      labels:
        app.kubernetes.io/component: radosgw
        app.kubernetes.io/name: ceph
        app.kubernetes.io/part-of: services
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ceph.kubernetes.progamesigner.dev/radosgw
                operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - radosgw
              - key: app.kubernetes.io/name
                operator: In
                values:
                - ceph
              - key: app.kubernetes.io/part-of
                operator: In
                values:
                - services
            topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: true
      initContainers:
      - name: chown
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          set -ex;

          cp -LRv /mnt/ceph/*.keyring /etc/ceph/;
          cp -LRv /mnt/ceph-conf/ceph.conf /etc/ceph/ceph.conf;

          chown -R 167:167 /etc/ceph;
        env:
        - name: CEPH_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        volumeMounts:
        - name: ceph
          mountPath: /mnt/ceph
          readOnly: true
        - name: ceph-conf
          mountPath: /mnt/ceph-conf
          readOnly: true
        - name: conf
          mountPath: /etc/ceph
        - name: data
          mountPath: /var/lib/ceph
      - name: setup
        image: ceph/ceph:latest
        command:
        - sh
        - -c
        - |
          set -ex;

          while ! ceph mon dump; do
            echo "Waiting for mon to be ready ...";
            sleep 5;
          done

          mkdir -p /var/lib/ceph/radosgw/ceph-${CEPH_NAME};

          if [ ! -f /var/lib/ceph/radosgw/ceph-${CEPH_NAME}/keyring ]; then
            ceph-authtool --create-keyring /var/lib/ceph/radosgw/ceph-${CEPH_NAME}/keyring --gen-key -n client.${CEPH_NAME};
            sleep 5;
            ceph auth add client.${CEPH_NAME} mon 'allow rw' osd 'allow rwx' -i /var/lib/ceph/radosgw/ceph-${CEPH_NAME}/keyring;
          fi

          chown -R 167:167 /var/lib/ceph/radosgw/ceph-${CEPH_NAME};
        env:
        - name: CEPH_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        volumeMounts:
        - name: conf
          mountPath: /etc/ceph
          readOnly: true
        - name: data
          mountPath: /var/lib/ceph
      containers:
      - name: radosgw
        image: ceph/ceph:latest
        command:
        - radosgw
        args:
        - --foreground
        - --id=$(CEPH_NAME)
        - --setgroup=ceph
        - --setuser=ceph
        env:
        - name: CEPH_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: http
          containerPort: 7480
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: conf
          mountPath: /etc/ceph
          readOnly: true
        - name: data
          mountPath: /var/lib/ceph
          readOnly: true
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: ceph
        hostPath:
          path: /etc/ceph
      - name: ceph-conf
        configMap:
          name: ceph
          items:
          - key: ceph.conf
            path: ceph.conf
      - name: conf
        emptyDir: {}
      - name: data
        hostPath:
          path: /var/lib/ceph
