---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: kube-router
  literals:
  - |
    cni-conf.json=
    {
      "cniVersion": "1.0.0",
      "name": "kube-router",
      "plugins": [
        {
          "name": "kube-router",
          "type": "bridge",
          "bridge": "kube-bridge",
          "isDefaultGateway": true,
          "hairpinMode": true,
          "ipam": {
            "type": "host-local"
          }
        }
      ]
    }
resources:
- daemonsets.yaml
- rbac.yaml
