---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: coredns
  files:
  - Corefile=Corefile
images:
- name: coredns/coredns
  newName: registry.k8s.io/coredns/coredns
  newTag: v1.10.1
resources:
- controllers.yaml
- rbac.yaml
