---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: coredns
  files:
  - Corefile=Corefile
  - resolv.conf=resolv.conf
  options:
    disableNameSuffixHash: true
resources:
- controllers.yaml
- rbac.yaml
