---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: coder
    app.kubernetes.io/name: coder
    app.kubernetes.io/part-of: components
  name: coder
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: coder
      app.kubernetes.io/name: coder
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: coder
        app.kubernetes.io/name: coder
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: coder
        image: coder/coder:latest
        env:
        - name: CODER_HTTP_ADDRESS
          value: 0.0.0.0:3000
        envFrom:
        - secretRef:
            name: coder
        ports:
        - name: http
          containerPort: 3000
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 64Mi
      serviceAccountName: default
