---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: coder
    app.kubernetes.io/name: coder
    app.kubernetes.io/part-of: components
  name: coder
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: coder
      app.kubernetes.io/name: coder
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: coder
        app.kubernetes.io/name: coder
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: coder
        image: coder/coder:latest
        env:
        - name: CODER_HTTP_ADDRESS
          value: 0.0.0.0:3000
        - name: CODER_TLS_ADDRESS
          value: 0.0.0.0:3443
        - name: CODER_TLS_CERT_FILE
          value: /etc/ssl/certs/coder/tls.crt
        - name: CODER_TLS_ENABLE
          value: 'true'
        - name: CODER_TLS_KEY_FILE
          value: /etc/ssl/certs/coder/tls.key
        envFrom:
        - secretRef:
            name: coder
        ports:
        - name: http
          containerPort: 3000
        - name: https
          containerPort: 3443
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: cert
          mountPath: /etc/ssl/certs/coder
          readOnly: true
        - name: service-account
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      - name: tailscale
        image: tailscale/tailscale:latest
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-coder
              key: TS_AUTHKEY
              optional: true
        - name: TS_SERVE_CONFIG
          value: /opt/tailscale-funnel/tailscale-funnel.json
        - name: TS_HOSTNAME
          value: coder
        - name: TS_KUBE_SECRET
          value: tailscale-coder-auth
        - name: TS_USERSPACE
          value: 'false'
        resources:
          limits:
            cpu: 300m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 16Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: service-account
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
        - name: tailscale-funnel
          mountPath: /opt/tailscale-funnel/tailscale-funnel.json
          subPath: tailscale-funnel.json
          readOnly: true
      serviceAccountName: default
      volumes:
      - name: cert
        secret:
          secretName: tls-dev-progamesigner
          defaultMode: 420
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
      - name: service-account
        projected:
          sources:
          - configMap:
              name: kube-root-ca.crt
          - downwardAPI:
              items:
              - path: namespace
                fieldRef:
                  fieldPath: metadata.namespace
          - serviceAccountToken:
              audience: https://kubernetes.default.svc.cluster.local
              expirationSeconds: 3600
              path: token
      - name: tailscale-funnel
        configMap:
          name: tailscale-funnel-coder
