---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tailscale-coder
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ''
  resourceNames:
  - tailscale-coder-auth
  resources:
  - secrets
  verbs:
  - get
  - patch
  - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tailscale-coder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale-coder
subjects:
- kind: ServiceAccount
  name: default
