---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: searxng
    app.kubernetes.io/name: searxng
    app.kubernetes.io/part-of: components
  name: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: searxng
      app.kubernetes.io/name: searxng
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: searxng
        app.kubernetes.io/name: searxng
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: searxng
        image: searxng/searxng:latest
        env:
        - name: FORCE_OWNERSHIP
          value: 'false'
        - name: SEARXNG_SECRET
          valueFrom:
            secretKeyRef:
              name: searxng
              key: SEARXNG_SECRET
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: cache
          mountPath: /var/cache/searxng
        - name: conf
          mountPath: /etc/searxng
          readOnly: true
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: cache
        emptyDir: {}
      - name: conf
        configMap:
          name: searxng
