---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: searxng
  files:
  - settings.yml=searxng.yaml
resources:
- controllers.yaml
secretGenerator:
- name: searxng
  envs:
  - searxng.env
