---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- browserless
- cloudflare
- gloomhaven
- proxy
- rss
images:
- name: browserless/browserless
  newName: browserless/chrome
  newTag: 1.58.0-chrome-stable
- name: cloudflare/cloudflared
  newName: cloudflare/cloudflared
  newTag: 2023.5.0
- name: gloomhaven/client
  newName: gloomhavensecretariat/ghs
  newTag: v0.73.0
- name: gloomhaven/server
  newName: gloomhavensecretariat/ghs-server
  newTag: v0.72.10
- name: proxy/proxy
  newName: amirdaaee/cloudflare-warp
  newTag: 2023.3.398-1
- name: rss/rsshub
  newName: diygod/rsshub
  newTag: 2023-09-04
namespace: default
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: gloomhaven
    spec:
      template:
        spec:
          volumes:
          - name: data
            emptyDir: null
            hostPath:
              type: DirectoryOrCreate
              path: /srv/gloomhaven-server
resources:
- services.yaml
