---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- browserless
- cloudflare
- proxy
- rss
images:
- name: browserless/browserless
  newName: browserless/chrome
  newTag: 1.58.0-chrome-stable
- name: cloudflare/cloudflared
  newName: cloudflare/cloudflared
  newTag: 2023.5.0
- name: proxy/proxy
  newName: amirdaaee/cloudflare-warp
  newTag: 2023.3.398-1
- name: rss/rsshub
  newName: diygod/rsshub
  newTag: 2023-04-25
namespace: default
resources:
- services.yaml
