---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- browserless
- rss
images:
- name: browserless/browserless
  newName: browserless/chrome
  newTag: 1.58.0-chrome-stable
- name: rss/rsshub
  newName: diygod/rsshub
  newTag: 2023-04-25
namespace: default
resources:
- certificates.yaml
- ingresses.yaml
- services.yaml
