---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- browserless
- cloudflare
- dify
- gloomhaven
- localai
- proxy
- rss
images:
- name: browserless/browserless
  newName: browserless/chrome
  newTag: 1.58.0-chrome-stable
- name: cloudflare/cloudflared
  newName: cloudflare/cloudflared
  newTag: 2024.3.0
- name: dify/api
  newName: langgenius/dify-api
  newTag: 0.5.10
- name: dify/worker
  newName: langgenius/dify-api
  newTag: 0.5.10
- name: dify/web
  newName: langgenius/dify-web
  newTag: 0.5.10
- name: dify/nginx
  newName: nginx
  newTag: 1.24-alpine
- name: gloomhaven/client
  newName: gloomhavensecretariat/ghs
  newTag: v0.73.0
- name: gloomhaven/server
  newName: gloomhavensecretariat/ghs-server
  newTag: v0.72.10
- name: localai/localai
  newName: quay.io/go-skynet/local-ai
  newTag: v2.8.0-ffmpeg
- name: proxy/proxy
  newName: amirdaaee/cloudflare-warp
  newTag: 2023.10.120-1
- name: rss/rsshub
  newName: diygod/rsshub
  newTag: 2024-02-10
namespace: default
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: gloomhaven
    spec:
      template:
        spec:
          volumes:
          - name: data
            emptyDir: null
            hostPath:
              type: DirectoryOrCreate
              path: /srv/gloomhaven-server
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: localai
    spec:
      template:
        spec:
          volumes:
          - name: artefacts
            emptyDir: null
            hostPath:
              type: DirectoryOrCreate
              path: /srv/localai-artefacts
          - name: data
            emptyDir: null
            hostPath:
              type: DirectoryOrCreate
              path: /srv/localai
resources:
- services.yaml
