---
apiVersion: v1
kind: Service
metadata:
  name: browserless
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app.kubernetes.io/component: browserless
    app.kubernetes.io/name: browserless
    app.kubernetes.io/part-of: applications
---
apiVersion: v1
kind: Service
metadata:
  name: rsshub
spec:
  ports:
  - name: http
    port: 1200
    targetPort: http
  selector:
    app.kubernetes.io/component: rsshub
    app.kubernetes.io/name: rss
    app.kubernetes.io/part-of: applications
