---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: ingress-nginx
  literals:
  - allow-snippet-annotations=true
  - enable-modsecurity=true
  - enable-ocsp=true
  - enable-owasp-modsecurity-crs=true
  - hsts-preload=true
  - proxy-body-size=1024m
  - server-tokens=false
  - ssl-ciphers=ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
  - ssl-dh-param=kube-system/ingress-nginx-dhparam
  - ssl-protocols=TLSv1.2 TLSv1.3
  - ssl-session-cache-size=15m
  - ssl-session-tickets=false
  - ssl-session-timeout=5m
  options:
    disableNameSuffixHash: true
- name: internal-ingress-nginx-tcp
  options:
    disableNameSuffixHash: true
- name: internal-ingress-nginx-udp
  options:
    disableNameSuffixHash: true
- name: external-ingress-nginx-tcp
  options:
    disableNameSuffixHash: true
- name: external-ingress-nginx-udp
  options:
    disableNameSuffixHash: true
resources:
- controllers.yaml
- rbac.yaml
secretGenerator:
- name: ingress-nginx-dhparam
  files:
  - dhparam.pem=files/dhparam.pem
  options:
    disableNameSuffixHash: true
