---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: rsshub
    app.kubernetes.io/name: rss
    app.kubernetes.io/part-of: applications
  name: rsshub
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: rsshub
      app.kubernetes.io/name: rss
      app.kubernetes.io/part-of: applications
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rsshub
        app.kubernetes.io/name: rss
        app.kubernetes.io/part-of: applications
    spec:
      automountServiceAccountToken: false
      containers:
      - name: rsshub
        image: rss/rsshub:latest
        env:
        - name: CACHE_TYPE
          value: redis
        - name: DEBUG_INFO
          value: 'false'
        - name: NODE_ENV
          value: production
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PROXY_URI
          value: http://proxy.default.svc.cluster.local:8080
        - name: PUPPETEER_WS_ENDPOINT
          value: ws://browserless.default.svc.cluster.local:3000
        - name: REDIS_URL
          value: redis://redis.default.svc.cluster.local:6379
        envFrom:
        - secretRef:
            name: rsshub
        ports:
        - name: http
          containerPort: 1200
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 300m
            memory: 256Mi
      serviceAccountName: default
