---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: windmill
  literals:
  - RUST_LOG=info
resources:
- controllers.yaml
secretGenerator:
- name: windmill
  literals:
  - DATABASE_URL=postgres://default:password@postgresql.default.svc.cluster.local:5432/windmill
