---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: cloudflared
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: components
  name: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: cloudflared
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cloudflared
        app.kubernetes.io/name: cloudflared
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: cloudflared
        image: network/cloudflared:latest
        args:
        - tunnel
        - run
        env:
        - name: NO_AUTOUPDATE
          value: 'true'
        - name: TUNNEL_METRICS
          value: 0.0.0.0:2000
        envFrom:
        - secretRef:
            name: cloudflared
        ports:
        - name: liveness
          containerPort: 2000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ready
            port: liveness
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
      enableServiceLinks: false
      serviceAccountName: default
