---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: n8n
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: components
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: n8n
      app.kubernetes.io/name: n8n
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: n8n
        app.kubernetes.io/name: n8n
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: init-n8n
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          set -ex;
          chown 1000:1000 /n8n-data
        volumeMounts:
        - name: data
          mountPath: /n8n-data
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
      containers:
      - name: n8n
        image: n8n/n8n:latest
        envFrom:
        - configMapRef:
            name: n8n
        - secretRef:
            name: n8n
        ports:
        - name: http
          containerPort: 5678
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: data
          mountPath: /home/node/.n8n
      serviceAccountName: default
      volumes:
      - name: data
        emptyDir: {}
