---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: n8n
  literals:
  - DB_TYPE=postgresdb
  - GENERIC_TIMEZONE=UTC
  - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
  - N8N_HIDE_USAGE_PAGE=true
  - N8N_MFA_ENABLED=false
  - N8N_RUNNERS_ENABLED=true
  - N8N_TEMPLATES_ENABLED=true
resources:
- controllers.yaml
secretGenerator:
- name: n8n
  envs:
  - n8n.env
  literals:
  - DB_POSTGRESDB_DATABASE=n8n
  - DB_POSTGRESDB_HOST=postgresql.default.svc.cluster.local
  - DB_POSTGRESDB_PASSWORD=password
  - DB_POSTGRESDB_PORT=5432
  - DB_POSTGRESDB_USER=default
