---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mon
spec:
  clusterIP: None
  ports:
  - name: ceph-mon
    port: 3300
    protocol: TCP
  - name: ceph-mon-v1
    port: 6789
    protocol: TCP
  selector:
    app.kubernetes.io/component: mon
    app.kubernetes.io/name: ceph
    app.kubernetes.io/part-of: kubernetes
