---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: phpmyadmin
    app.kubernetes.io/name: phpmyadmin
    app.kubernetes.io/part-of: components
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: phpmyadmin
      app.kubernetes.io/name: phpmyadmin
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: phpmyadmin
        app.kubernetes.io/name: phpmyadmin
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        envFrom:
        - secretRef:
            name: phpmyadmin
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 64Mi
