---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- deployments.yaml
- services.yaml
secretGenerator:
- literals:
  - POSTGRES_USER=default
  - POSTGRES_PASSWORD=password
  name: postgresql
