---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/name: tailscale
    app.kubernetes.io/part-of: components
  name: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: tailscale
      app.kubernetes.io/name: tailscale
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tailscale
        app.kubernetes.io/name: tailscale
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: true
      containers:
      - name: tailscale
        image: tailscale/tailscale:latest
        env:
        - name: TS_KUBE_SECRET
          value: tailscale-state
        envFrom:
        - secretRef:
            name: tailscale
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
      serviceAccountName: tailscale
