---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- controllers.yaml
- rbac.yaml
secretGenerator:
- name: protonvpn
  envs:
  - protonvpn.env
- name: tailscale
  envs:
  - tailscale.env
