---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tailscale
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ''
  resourceNames:
  - tailscale-state
  resources:
  - secrets
  verbs:
  - get
  - patch
  - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tailscale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale
subjects:
- kind: ServiceAccount
  name: tailscale
