---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tailscale-protonvpn
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ''
  resourceNames:
  - tailscale-protonvpn-ch
  - tailscale-protonvpn-de
  - tailscale-protonvpn-jp
  - tailscale-protonvpn-tw
  - tailscale-protonvpn-us
  resources:
  - secrets
  verbs:
  - get
  - patch
  - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tailscale-protonvpn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale-protonvpn
subjects:
- kind: ServiceAccount
  name: default
