---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: seafile
    app.kubernetes.io/part-of: components
  name: seafile-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/name: seafile
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
        app.kubernetes.io/name: seafile
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: true
      initContainers:
      - name: chown
        image: busybox:latest
        command:
        - sh
        - -c
        - set -ex;

          chown -R root:root /shared
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        volumeMounts:
        - name: data
          mountPath: /shared
      - name: certificates
        image: seafile/backend:latest
        command:
        - update-ca-certificates
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        volumeMounts:
        - name: ca
          mountPath: /usr/local/share/ca-certificates
          readOnly: true
        - name: certs
          mountPath: /etc/ssl/certs
      containers:
      - name: seafile
        image: seafile/backend:latest
        env:
        - name: CLUSTER_MODE
          value: 'backend'
        - name: CLUSTER_SERVER
          value: 'true'
        envFrom:
        - configMapRef:
            name: seafile
        - secretRef:
            name: seafile
        resources:
          limits:
            cpu: 300m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: certs
          mountPath: /etc/ssl/certs
          readOnly: true
        - name: data
          mountPath: /shared
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: ca
        secret:
          secretName: tls-ceph-radosgw
          defaultMode: 420
          items:
          - key: ca.crt
            path: ca.crt
      - name: certs
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: seafile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: seafile
    app.kubernetes.io/part-of: components
  name: seafile-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/name: seafile
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        app.kubernetes.io/name: seafile
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: true
      initContainers:
      - name: chown
        image: busybox:latest
        command:
        - sh
        - -c
        - set -ex;

          chown -R root:root /shared
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        volumeMounts:
        - name: data
          mountPath: /shared
      containers:
      - name: seafile
        image: seafile/frontend:latest
        env:
        - name: CLUSTER_MODE
          value: 'frontend'
        - name: CLUSTER_SERVER
          value: 'true'
        envFrom:
        - configMapRef:
            name: seafile
        - secretRef:
            name: seafile
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: data
          mountPath: /shared
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: seafile
