---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: multus
    app.kubernetes.io/name: multus
    app.kubernetes.io/part-of: cluster
  name: multus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: multus
      app.kubernetes.io/name: multus
      app.kubernetes.io/part-of: cluster
  template:
    metadata:
      labels:
        app.kubernetes.io/component: multus
        app.kubernetes.io/name: multus
        app.kubernetes.io/part-of: cluster
    spec:
      initContainers:
      - name: install-cni
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          set -ex;
          mkdir -p /etc/cni/net.d/multus.d;
          cat > /etc/cni/net.d/multus.d/multus.kubeconfig <<EOF
          apiVersion: v1
          kind: Config
          clusters:
          - name: multus
            cluster:
              server: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}
              certificate-authority-data: $(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt | base64 | tr -d '\n')
          users:
          - name: multus
            user:
              token: $(cat /var/run/secrets/kubernetes.io/serviceaccount/token | tr -d '\n')
          contexts:
          - name: multus
            context:
              cluster: multus
              user: multus
          current-context: multus
          EOF
        resources:
          requests:
            cpu: 50m
            memory: 16Mi
        volumeMounts:
        - name: cni-conf-dir
          mountPath: /etc/cni/net.d
      containers:
      - name: multus
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:v4.0.1
        args:
        - --cni-bin-dir=/opt/cni/bin
        - --cni-conf-dir=/etc/cni/net.d
        - --multus-conf-file=/etc/multus/10-multus.conflist
        - --namespace-isolation=true
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni-bin-dir
          mountPath: /opt/cni/bin
        - name: cni-conf-dir
          mountPath: /etc/cni/net.d
        - name: multus
          mountPath: /etc/multus
      hostNetwork: true
      priorityClassName: system-node-critical
      serviceAccount: multus
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: cni-bin-dir
        hostPath:
          path: /opt/cni/bin
      - name: cni-conf-dir
        hostPath:
          path: /etc/cni/net.d
      - name: multus
        configMap:
          name: multus
          items:
          - key: cni-conf.json
            path: 10-multus.conflist
