---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: multus
    app.kubernetes.io/name: multus
    app.kubernetes.io/part-of: cluster
  name: multus
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/component: multus
    app.kubernetes.io/name: multus
    app.kubernetes.io/part-of: cluster
  name: multus
rules:
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - pods
  - pods/status
  verbs:
  - get
  - update
- apiGroups:
  - ''
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/component: kube-router
    app.kubernetes.io/name: kube-router
    app.kubernetes.io/part-of: cluster
  name: multus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multus
subjects:
- kind: ServiceAccount
  name: multus
