---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: muninn
  literals:
  - OBSIDIAN_DEVICE_NAME=Obsidian
resources:
- controllers.yaml
- storages.yaml
secretGenerator:
- name: muninn
  envs:
  - muninn.env
  files:
  - tokens.json
