---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: progamesigner@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - http01:
        ingress:
          class: external-ingress
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cert-manager-cloudflare
            key: API_TOKEN
      selector:
        dnsZones:
        - progamesigner.dev
