---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- certificates.yaml
- issuers.yaml
secretGenerator:
- name: cert-manager-cloudflare
  envs:
  - cloudflare.env
  options:
    disableNameSuffixHash: true
