---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: vscode-server
    app.kubernetes.io/name: vscode-server
    app.kubernetes.io/part-of: components
  name: vscode-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: vscode-server
      app.kubernetes.io/name: vscode-server
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: vscode-server
        app.kubernetes.io/name: vscode-server
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: chown
        image: vscode/server:latest
        command:
        - sh
        - -c
        - |
          set -ex;

          chown -R vscode:vscode /home/vscode/.vscode-cli;
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /home/vscode/.vscode-cli
      containers:
      - name: vscode-server
        image: vscode/server:latest
        args:
        - --accept-server-license-terms
        - --name=default
        env:
        - name: VSCODE_CLI_USE_FILE_KEYCHAIN
          value: 'true'
        resources:
          limits:
            cpu: 4000m
            memory: 16Gi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: data
          mountPath: /home/vscode/.vscode-cli
        - name: files
          mountPath: /home/vscode/codes
          subPath: developer/projects
        - name: files
          mountPath: /home/vscode/.gitattributes
          subPath: dotfiles/git/attributes
        - name: files
          mountPath: /home/vscode/.gitignore
          subPath: dotfiles/git/ignore
        - name: files-git
          mountPath: /home/vscode/.gitconfig
          subPath: gitconfig
        - name: files-gpg
          mountPath: /home/vscode/.gnupg
        - name: files-ssh
          mountPath: /home/vscode/.ssh
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vscode-server
      - name: files
        persistentVolumeClaim:
          claimName: syncthing
      - name: files-git
        persistentVolumeClaim:
          claimName: dev-tunnel-git
      - name: files-gpg
        persistentVolumeClaim:
          claimName: dev-tunnel-gpg
      - name: files-ssh
        persistentVolumeClaim:
          claimName: dev-tunnel-ssh
