---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: vscode-server
    app.kubernetes.io/name: vscode-server
    app.kubernetes.io/part-of: components
  name: vscode-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: vscode-server
      app.kubernetes.io/name: vscode-server
      app.kubernetes.io/part-of: components
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: vscode-server
        app.kubernetes.io/name: vscode-server
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: vscode-server
        image: vscode/server:latest
        args:
        - --accept-server-license-terms
        - --name=$(VSCODE_SERVER_NAME)
        env:
        - name: VSCODE_CLI_DATA_DIR
          value: /opt/vscode-server
        - name: VSCODE_SERVER_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
          requests:
            cpu: 300m
            memory: 512Mi
        volumeMounts:
        - name: data
          mountPath: /opt/vscode-server
        - name: files
          mountPath: /home/vscode/codespaces
          subPath: codespaces
        - name: files
          mountPath: /home/vscode/dotfiles
          subPath: dotfiles
        - name: files
          mountPath: /home/vscode/.docker
          subPath: dotfiles/.docker
        - name: files
          mountPath: /home/vscode/.kube
          subPath: dotfiles/.kubernetes
        - name: files
          mountPath: /home/vscode/.ssh
          subPath: dotfiles/.ssh
      serviceAccountName: default
      volumes:
      - name: data
        emptyDir: {}
      - name: files
        emptyDir: {}
