---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- browserless
- ceph
- elasticsearch
- localai
- mariadb
- mongodb
- postgresql
- redis
images:
- name: browserless/browserless
  newName: ghcr.io/browserless/multi
  newTag: v2.32.1
- name: ceph/ceph
  newName: quay.io/ceph/ceph
  newTag: v20.1.1
- name: elasticsearch/elasticsearch
  newName: docker.elastic.co/elasticsearch/elasticsearch
  newTag: 8.7.0
- name: mariadb/mariadb
  newName: mariadb
  newTag: 10.11.2
- name: mongodb/mongodb
  newName: mongo
  newTag: 6.0.5
- name: postgresql/postgresql-v18
  newName: postgres
  newTag: 18.3-alpine
- name: redis/redis
  newName: redis
  newTag: 8.0.0-alpine
namespace: default
resources:
- certificates.yaml
- services.yaml
