---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: weaviate
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/part-of: services
  name: weaviate
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: weaviate
      app.kubernetes.io/name: weaviate
      app.kubernetes.io/part-of: services
  serviceName: headless-weaviate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: weaviate
        app.kubernetes.io/name: weaviate
        app.kubernetes.io/part-of: services
    spec:
      automountServiceAccountToken: false
      containers:
      - name: weaviate
        image: weaviate/weaviate:latest
        env:
        - name: PERSISTENCE_DATA_PATH
          value: /var/lib/weaviate
        envFrom:
        - secretRef:
            name: weaviate
        ports:
        - name: weaviate
          containerPort: 8080
          protocol: TCP
        - name: grpc
          containerPort: 8081
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/weaviate
        resources:
          limits:
            cpu: 2000m
            memory: 8Gi
          requests:
            cpu: 500m
            memory: 1Gi
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: data
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 128Gi
      storageClassName: ceph-rbd
