---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/component: database
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/instance: mariadb
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/instance: mariadb
        app.kubernetes.io/component: database
    spec:
      automountServiceAccountToken: false
      containers:
      - name: mariadb
        image: mariadb:latest
        envFrom:
        - secretRef:
            name: mariadb
        ports:
        - name: mariadb
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
      volumes:
      - name: data
        emptyDir: {}
