---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - name: mariadb
    port: 3306
    targetPort: mariadb
  selector:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/component: database
  type: ClusterIP
