---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: mongodb-compass
    app.kubernetes.io/name: mongodb-compass
    app.kubernetes.io/part-of: components
  name: mongodb-compass
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mongodb-compass
      app.kubernetes.io/name: mongodb-compass
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mongodb-compass
        app.kubernetes.io/name: mongodb-compass
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: mongodb-compass
        image: mongodb/compass:latest
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 64Mi
      enableServiceLinks: false
      serviceAccountName: default
