---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: mongodb-compass
    app.kubernetes.io/name: mongodb-compass
    app.kubernetes.io/part-of: components
  name: mongodb-compass
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mongodb-compass
      app.kubernetes.io/name: mongodb-compass
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mongodb-compass
        app.kubernetes.io/name: mongodb-compass
        app.kubernetes.io/part-of: components
    spec:
      containers:
      - name: mongodb-compass
        image: mongodb/compass:latest
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 32Mi
      #   volumeMounts:
      #   - name: data
      #     mountPath: /data
      # volumes:
      # - name: data
      #   emptyDir: {}
