---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  - name: dns-tls
    port: 853
    targetPort: dns-tls
  - name: dnscrypt
    port: 5443
    targetPort: dnscrypt
  selector:
    app.kubernetes.io/component: adguard-home
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  ports:
  - name: http
    port: 8123
    targetPort: http
  selector:
    app.kubernetes.io/component: home-assistant
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
spec:
  ports:
  - name: http
    port: 8384
    targetPort: http
  selector:
    app.kubernetes.io/component: syncthing
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/component: unifi-controller
    app.kubernetes.io/name: unifi-controller
    app.kubernetes.io/part-of: components

---
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: adguard-home
spec:
  action:
    pass: adguard-home
  listener:
    name: dns-over-tls
    protocol: TCP
  upstreams:
  - name: adguard-home
    service: adguard-home
    port: 853
---
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: adguard-home-udp
spec:
  action:
    pass: adguard-home
  listener:
    name: dns-over-tls-udp
    protocol: UDP
  upstreams:
  - name: adguard-home
    service: adguard-home
    port: 853
  upstreamParameters:
    udpRequests: 1
    udpResponses: 1
