---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  - name: dns-tls
    port: 853
    targetPort: dns-tls
  - name: dnscrypt
    port: 5443
    targetPort: dnscrypt
  selector:
    app.kubernetes.io/component: adguard-home
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  ports:
  - name: http
    port: 8123
    targetPort: http
  selector:
    app.kubernetes.io/component: home-assistant
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
spec:
  ports:
  - name: http
    port: 8384
    targetPort: http
  selector:
    app.kubernetes.io/component: syncthing
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/component: unifi-controller
    app.kubernetes.io/name: unifi-controller
    app.kubernetes.io/part-of: components
