---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home
spec:
  ports:
  - name: https-tcp
    port: 443
    protocol: TCP
    targetPort: https-tcp
  - name: https-udp
    port: 443
    protocol: UDP
    targetPort: https-udp
  - name: dns-tls-tcp
    port: 853
    protocol: TCP
    targetPort: dns-tls-tcp
  - name: dns-tls-udp
    port: 853
    protocol: UDP
    targetPort: dns-tls-udp
  - name: dnscrypt-tcp
    port: 5443
    protocol: TCP
    targetPort: dnscrypt-tcp
  - name: dnscrypt-udp
    port: 5443
    protocol: UDP
    targetPort: dnscrypt-udp
  selector:
    app.kubernetes.io/component: adguard-home
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: apprise
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: apprise
    app.kubernetes.io/name: apprise
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: coder
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: coder
    app.kubernetes.io/name: coder
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
spec:
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: home-assistant
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: dify-api
spec:
  ports:
  - name: http
    port: 5001
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: dify-plugin-daemon
spec:
  ports:
  - name: http
    port: 5002
    protocol: TCP
    targetPort: http
  - name: remote-plugins
    port: 5003
    protocol: TCP
    targetPort: remote-plugins
  selector:
    app.kubernetes.io/component: plugin-daemon
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: dify-sandbox
spec:
  ports:
  - name: http
    port: 8194
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: sandbox
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: dify-ssrf-proxy
spec:
  ports:
  - name: proxy
    port: 3128
    protocol: TCP
    targetPort: proxy
  selector:
    app.kubernetes.io/component: ssrf-proxy
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: dify-web
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: web
    app.kubernetes.io/name: dify
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: firecrawl
spec:
  ports:
  - name: http
    port: 3002
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: firecrawl
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: gloomhaven
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: secretariat
    app.kubernetes.io/name: gloomhaven
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: home-assistant
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: metascraper
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: metascraper
    app.kubernetes.io/name: metascraper
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-compass
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: mongodb-compass
    app.kubernetes.io/name: mongodb-compass
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: pgadmin
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: phpmyadmin
    app.kubernetes.io/name: phpmyadmin
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  ports:
  - name: socks
    port: 1080
    protocol: TCP
    targetPort: socks
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: proxy
  selector:
    app.kubernetes.io/component: cloudflare-warp
    app.kubernetes.io/name: proxy
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-ch
spec:
  ports:
  - name: socks
    port: 1080
    protocol: TCP
    targetPort: socks
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: proxy
  selector:
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/name: protonvpn
    app.kubernetes.io/part-of: components
    kubernetes.progamesigner.dev/vpn-region: ch
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-de
spec:
  ports:
  - name: socks
    port: 1080
    protocol: TCP
    targetPort: socks
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: proxy
  selector:
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/name: protonvpn
    app.kubernetes.io/part-of: components
    kubernetes.progamesigner.dev/vpn-region: de
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-jp
spec:
  ports:
  - name: socks
    port: 1080
    protocol: TCP
    targetPort: socks
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: proxy
  selector:
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/name: protonvpn
    app.kubernetes.io/part-of: components
    kubernetes.progamesigner.dev/vpn-region: jp
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-tw
spec:
  ports:
  - name: socks
    port: 1080
    protocol: TCP
    targetPort: socks
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: proxy
  selector:
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/name: protonvpn
    app.kubernetes.io/part-of: components
    kubernetes.progamesigner.dev/vpn-region: tw
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-us
spec:
  ports:
  - name: socks
    port: 1080
    protocol: TCP
    targetPort: socks
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: proxy
  selector:
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/name: protonvpn
    app.kubernetes.io/part-of: components
    kubernetes.progamesigner.dev/vpn-region: us
---
apiVersion: v1
kind: Service
metadata:
  name: redis-insight
spec:
  ports:
  - name: http
    port: 5540
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: redis-insight
    app.kubernetes.io/name: redis-insight
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: rsshub
spec:
  ports:
  - name: http
    port: 1200
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: rsshub
    app.kubernetes.io/name: rsshub
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
spec:
  ports:
  - name: http
    port: 8384
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: syncthing
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-network
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: unifi-network
    app.kubernetes.io/name: unifi-network
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: windmill
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: windmill
    app.kubernetes.io/name: windmill
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: windmill-api
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: windmill
    app.kubernetes.io/name: windmill
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: windmill-lsp
spec:
  ports:
  - name: lsp
    port: 3001
    protocol: TCP
    targetPort: lsp
  selector:
    app.kubernetes.io/component: windmill-lsp
    app.kubernetes.io/name: windmill
    app.kubernetes.io/part-of: components
---
apiVersion: v1
kind: Service
metadata:
  name: local-dns
spec:
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: dns-tcp
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  selector:
    app.kubernetes.io/component: adguard-home
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/part-of: components
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: local-relaysrv
spec:
  ports:
  - name: relaysrv
    port: 22067
    protocol: TCP
    targetPort: relaysrv
  - name: relaysrv-status
    port: 22070
    protocol: TCP
    targetPort: relaysrv-status
  selector:
    app.kubernetes.io/component: syncthing-relay
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/part-of: components
  type: LoadBalancer
