---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workflow-mount-ssh
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 16Mi
  storageClassName: ceph-cephfs
