---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-conf-git
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 16Mi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-conf-gpg
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 16Mi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-conf-ssh
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 16Mi
  storageClassName: ceph-cephfs
