---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: metallb-excludel2
  literals:
  - |
    excludel2.yaml=
    announcedInterfacesToExclude:
    - ^cali.*
    - ^nodelocaldns.*
    - ^tunl.*
    - cbr.*
    - cni.*
    - docker.*
    - dummy.*
    - flannel.*
    - kube-ipvs.*
    - lo
    - lxcbr.*
    - veth.*
    - virbr.*
images:
- name: metallb/controller
  newName: quay.io/metallb/controller
  newTag: v0.14.9
- name: metallb/speaker
  newName: quay.io/metallb/speaker
  newTag: v0.14.9
resources:
- https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/crd/bases/metallb.io_bfdprofiles.yaml
- https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/crd/bases/metallb.io_bgpadvertisements.yaml
- https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/crd/bases/metallb.io_bgppeers.yaml
- https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/crd/bases/metallb.io_communities.yaml
- https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/crd/bases/metallb.io_ipaddresspools.yaml
- https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/crd/bases/metallb.io_l2advertisements.yaml
- https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/crd/bases/metallb.io_servicel2statuses.yaml

- controllers.yaml
- rbac.yaml
