---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: redis-insight
    app.kubernetes.io/name: redis-insight
    app.kubernetes.io/part-of: components
  name: redis-insight
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: redis-insight
      app.kubernetes.io/name: redis-insight
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis-insight
        app.kubernetes.io/name: redis-insight
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: redis-insight
        image: redis/insight:latest
        envFrom:
        - secretRef:
            name: redis-insight
        ports:
        - name: http
          containerPort: 5540
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 64Mi
      enableServiceLinks: false
      serviceAccountName: default
