---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: claude-code
    app.kubernetes.io/name: sleipnir
    app.kubernetes.io/part-of: components
  name: sleipnir
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: claude-code
      app.kubernetes.io/name: sleipnir
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: claude-code
        app.kubernetes.io/name: sleipnir
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: claude-code
        image: claude-code/claude-code:latest
        imagePullPolicy: Always
        args:
        - claude
        - --channels
        - plugin:telegram@claude-plugins-official
        - --continue
        - --remote-control
        envFrom:
        - secretRef:
            name: sleipnir
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
        stdin: true
        tty: true
        volumeMounts:
        - name: conf-github
          mountPath: /home/ubuntu/.config/gh
        - name: data
          mountPath: /workspace
        - name: data-claude
          mountPath: /home/ubuntu/.claude
      enableServiceLinks: false
      securityContext:
        fsGroup: 1000
      serviceAccountName: default
      volumes:
      - name: conf-github
        persistentVolumeClaim:
          claimName: dev-conf-github
      - name: data
        persistentVolumeClaim:
          claimName: sleipnir
      - name: data-claude
        persistentVolumeClaim:
          claimName: dev-data-claude
