---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- controllers.yaml
- storages.yaml
secretGenerator:
- name: sleipnir-urd
  envs:
  - sleipnir-urd.env
- name: sleipnir-verdandi
  envs:
  - sleipnir-verdandi.env
- name: sleipnir-skuld
  envs:
  - sleipnir-skuld.env
