---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-hvergelmir
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-mimisbrunnr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-skuld
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-urd
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-urdarbrunnr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-verdandi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  storageClassName: ceph-cephfs
