---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-alfheim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-asgard
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-helheim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-jotunheim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-midgard
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-muspelheim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-nidavellir
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-niflheim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-skuld
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-svartalfheim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-urd
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-vanaheim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sleipnir-verdandi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  storageClassName: ceph-cephfs
