---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: cert-manager/cainjector
  newName: quay.io/jetstack/cert-manager-cainjector
  newTag: v1.19.0
- name: cert-manager/controller
  newName: quay.io/jetstack/cert-manager-controller
  newTag: v1.19.0
- name: cert-manager/webhook
  newName: quay.io/jetstack/cert-manager-webhook
  newTag: v1.19.0
resources:
- controllers.yaml
- rbac.yaml
- https://github.com/cert-manager/cert-manager/releases/download/v1.19.0/cert-manager.crds.yaml
