---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: elasticsearch
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: services
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: elasticsearch
      app.kubernetes.io/name: elasticsearch
      app.kubernetes.io/part-of: services
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: elasticsearch
        app.kubernetes.io/name: elasticsearch
        app.kubernetes.io/part-of: services
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: init-elasticsearch
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          set -ex;
          chown 1000:1000 /usr/share/elasticsearch/data;
        envFrom:
        - secretRef:
            name: elasticsearch
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      containers:
      - name: elasticsearch
        image: elasticsearch/elasticsearch:latest
        envFrom:
        - secretRef:
            name: elasticsearch
        ports:
        - name: elasticsearch
          containerPort: 9200
        - name: transport
          containerPort: 9300
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        resources:
          limits:
            cpu: 1500m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 64Mi
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: data
        emptyDir: {}
