---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: elasticsearch
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: services
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: elasticsearch
      app.kubernetes.io/name: elasticsearch
      app.kubernetes.io/part-of: services
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: elasticsearch
        app.kubernetes.io/name: elasticsearch
        app.kubernetes.io/part-of: services
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: chown
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          set -ex;
          chown 1000:1000 /usr/share/elasticsearch/data;
        envFrom:
        - secretRef:
            name: elasticsearch
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: setup
        image: elasticsearch/elasticsearch:latest
        command:
        - sh
        - -c
        - |
          bin/elasticsearch-plugin install --batch analysis-smartcn
        envFrom:
        - secretRef:
            name: elasticsearch
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: plugins
          mountPath: /usr/share/elasticsearch/plugins
      containers:
      - name: elasticsearch
        image: elasticsearch/elasticsearch:latest
        envFrom:
        - secretRef:
            name: elasticsearch
        ports:
        - name: elasticsearch
          containerPort: 9200
          protocol: TCP
        - name: transport
          containerPort: 9300
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 150m
            memory: 256Mi
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: plugins
          mountPath: /usr/share/elasticsearch/plugins
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: data
        emptyDir: {}
      - name: plugins
        emptyDir: {}
