---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: node-red
    app.kubernetes.io/name: node-red
    app.kubernetes.io/part-of: components
  name: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: node-red
      app.kubernetes.io/name: node-red
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: node-red
        app.kubernetes.io/name: node-red
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: init-node-red
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          set -ex;
          chown 1000:1000 /data
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
      containers:
      - name: node-red
        image: node-red/node-red:latest
        ports:
        - name: http
          containerPort: 1880
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: data
          mountPath: /data
        - name: files
          mountPath: /srv
          readOnly: true
      serviceAccountName: default
      volumes:
      - name: data
        emptyDir: {}
      - name: files
        emptyDir: {}
