---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: syncthing
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/part-of: cluster
  name: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: syncthing
      app.kubernetes.io/name: syncthing
      app.kubernetes.io/part-of: cluster
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: syncthing
        app.kubernetes.io/name: syncthing
        app.kubernetes.io/part-of: cluster
    spec:
      automountServiceAccountToken: false
      containers:
      - name: syncthing
        image: syncthing:latest
        ports:
        - name: gui
          containerPort: 8384
        - name: syncthing
          containerPort: 22000
        - name: syncthing-udp
          containerPort: 22000
          protocol: UDP
        - name: discovery-udp
          containerPort: 21027
          protocol: UDP
        volumeMounts:
        - name: syncthing
          mountPath: /var/syncthing
        resources:
          limits:
            cpu: 3000m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 128Mi
      - name: syncthing-relay
        image: syncthing-relay:latest
        args:
        - -global-rate=2000000
        - -provided-by='0x148 <https://0x148.com>'
        ports:
        - name: relay
          containerPort: 22067
        - name: status
          containerPort: 22070
        volumeMounts:
        - name: syncthing-relay
          mountPath: /var/strelaysrv
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 32Mi
      serviceAccountName: default
      volumes:
      - name: syncthing
        emptyDir: {}
      - name: syncthing-relay
        emptyDir: {}
