---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: localai
    app.kubernetes.io/name: localai
    app.kubernetes.io/part-of: applications
  name: localai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: localai
      app.kubernetes.io/name: localai
      app.kubernetes.io/part-of: applications
  template:
    metadata:
      labels:
        app.kubernetes.io/component: localai
        app.kubernetes.io/name: localai
        app.kubernetes.io/part-of: applications
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: builder
        image: localai/localai:latest
        command:
        - sh
        - -c
        - |
          set -ex;

          touch /built/version

          BUILT_VERSION=$(cat /built/version)
          IMAGE_VERSION=$(/build/local-ai --version)

          if [ "$BUILT_VERSION" != "$IMAGE_VERSION" ]; then
            rm -f /built/local-ai
            make build -j4
            cp local-ai /built/local-ai
            /built/local-ai --version > /built/version
          fi
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi
          requests:
            cpu: 300m
            memory: 128Mi
        volumeMounts:
        - name: artefacts
          mountPath: /built
      containers:
      - name: localai
        image: localai/localai:latest
        command:
        - /build/local-ai
        - --parallel-requests
        env:
        - name: GALLERIES
          value: |-
            [
                {
                    "url": "github:progamesigner/localai-model-gallery/index.yaml",
                    "name": "progamesigner-model-gallery"
                },
                {
                    "name": "model-gallery",
                    "url": "github:go-skynet/model-gallery/index.yaml"
                },
                {
                    "url": "github:go-skynet/model-gallery/huggingface.yaml",
                    "name": "huggingface"
                }
            ]
        - name: MODELS_PATH
          value: /models
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: 4000m
            memory: 16Gi
          requests:
            cpu: 300m
            memory: 128Mi
        volumeMounts:
        - name: artefacts
          mountPath: /build/local-ai
          readOnly: true
          subPath: local-ai
        - name: data
          mountPath: /models
      serviceAccountName: default
      volumes:
      - name: artefacts
        emptyDir: {}
      - name: data
        emptyDir: {}
