---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: localai
    app.kubernetes.io/name: localai
    app.kubernetes.io/part-of: applications
  name: localai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: localai
      app.kubernetes.io/name: localai
      app.kubernetes.io/part-of: applications
  template:
    metadata:
      labels:
        app.kubernetes.io/component: localai
        app.kubernetes.io/name: localai
        app.kubernetes.io/part-of: applications
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: builder
        image: localai/localai:latest
        command:
        - sh
        - -c
        - |
          set -ex;
          make build -j4
          cp local-ai /built/local-ai
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
          requests:
            cpu: 300m
            memory: 128Mi
        volumeMounts:
        - name: artefacts
          mountPath: /built
      containers:
      - name: localai
        image: localai/localai:latest
        command:
        - /build/local-ai
        env:
        - name: GALLERIES
          value: |-
            [
                {
                    "name": "model-gallery",
                    "url": "github:go-skynet/model-gallery/index.yaml"
                },
                {
                    "url": "github:go-skynet/model-gallery/huggingface.yaml",
                    "name": "huggingface"
                }
            ]
        - name: MODELS_PATH
          value: /models
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: 4000m
            memory: 20Gi
          requests:
            cpu: 300m
            memory: 128Mi
        volumeMounts:
        - name: artefacts
          mountPath: /build/local-ai
          subPath: local-ai
        - name: data
          mountPath: /models
      serviceAccountName: default
      volumes:
      - name: artefacts
        emptyDir: {}
      - name: data
        emptyDir: {}
