---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: obsidian
    app.kubernetes.io/name: obsidian
    app.kubernetes.io/part-of: components
  name: obsidian
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: obsidian
      app.kubernetes.io/name: obsidian
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: obsidian
        app.kubernetes.io/name: obsidian
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: init
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          set -ex;

          for path in /mnt/conf-persist/obsidian-headless/sync/*/config.json; do
            if [ -f $path ]; then
              relpath=${path#/mnt/conf-persist/}
              mkdir -p /mnt/conf/$(dirname $relpath)
              cp -Lv $path /mnt/conf/$relpath
            fi
          done

          chown -R 1000:1000 /mnt/conf;
        volumeMounts:
        - name: conf
          mountPath: /mnt/conf
        - name: conf-persist
          mountPath: /mnt/conf-persist
      containers:
      - name: obsidian
        image: obsidian/obsidian:latest
        env:
        - name: PGID
          value: '1000'
        - name: PUID
          value: '1000'
        envFrom:
        - configMapRef:
            name: obsidian
        - secretRef:
            name: obsidian
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - |
                set -ex;

                for path in /home/obsidian/.config/obsidian-headless/sync/*/config.json; do
                  if [ -f $path ]; then
                    relpath=${path#/home/obsidian/.config/}
                    mkdir -p /mnt/conf-persist/$(dirname $relpath)
                    cp -Lv $path /mnt/conf-persist/$relpath || true
                  fi
                done
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 300m
            memory: 128Mi
        volumeMounts:
        - name: conf
          mountPath: /home/obsidian/.config
        - name: conf-persist
          mountPath: /mnt/conf-persist
        - name: data
          mountPath: /vault
      enableServiceLinks: false
      securityContext:
        fsGroup: 1000
      serviceAccountName: default
      volumes:
      - name: conf
        emptyDir:
          medium: Memory
      - name: conf-persist
        persistentVolumeClaim:
          claimName: obsidian-config
      - name: data
        persistentVolumeClaim:
          claimName: obsidian
