---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: obsidian
  literals:
  - DEVICE_NAME=Obsidian
resources:
- controllers.yaml
- storages.yaml
secretGenerator:
- name: obsidian
  envs:
  - obsidian.env
