---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  storageClassName: ceph-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-config
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Mi
  storageClassName: ceph-cephfs
