---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: pgadmin
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/part-of: components
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: pgadmin
      app.kubernetes.io/name: pgadmin
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: pgadmin
        app.kubernetes.io/name: pgadmin
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: chown
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          set -ex;
          chown -R 5050 /var/lib/pgadmin;
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /var/lib/pgadmin
      containers:
      - name: pgadmin
        image: pgadmin/pgadmin:latest
        env:
        - name: GUNICORN_THREADS
          value: '2'
        - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
          value: 'False'
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: 'False'
        - name: PGADMIN_DEFAULT_EMAIL
          value: pgadmin4@pgadmin.org
        - name: PGADMIN_DEFAULT_PASSWORD
          value: pgadmin4@pgadmin.org
        - name: PGADMIN_DISABLE_POSTFIX
          value: 'True'
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/pgadmin
      - name: tailscale
        image: network/tailscale:latest
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: KUBERNETES_SERVICE_HOST
          value: ''
        - name: KUBERNETES_SERVICE_PORT
          value: ''
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-app-connector
              key: TS_AUTHKEY
        - name: TS_EXTRA_ARGS
          value: --accept-routes=true
        - name: TS_KUBE_SECRET
          value: ''
        - name: TS_USERSPACE
          value: 'false'
        livenessProbe:
          exec:
            command:
            - tailscale
            - ip
            - --4
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            drop:
            - ALL
          privileged: true
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pgadmin
