---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: pgadmin
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/part-of: components
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: pgadmin
      app.kubernetes.io/name: pgadmin
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: pgadmin
        app.kubernetes.io/name: pgadmin
        app.kubernetes.io/part-of: components
    spec:
      initContainers:
      - name: chown
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          set -ex;
          chown -R 5050 /var/lib/pgadmin;
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /var/lib/pgadmin
      containers:
      - name: pgadmin
        image: pgadmin/pgadmin:latest
        env:
        - name: GUNICORN_THREADS
          value: '2'
        - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
          value: 'False'
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: 'False'
        - name: PGADMIN_DEFAULT_EMAIL
          value: pgadmin4@pgadmin.org
        - name: PGADMIN_DEFAULT_PASSWORD
          value: pgadmin4@pgadmin.org
        - name: PGADMIN_DISABLE_POSTFIX
          value: 'True'
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 32Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/pgadmin
      volumes:
      - name: data
        emptyDir: {}
