---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: adguard-home
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/part-of: components
  name: adguard-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: adguard-home
      app.kubernetes.io/name: adguard-home
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: adguard-home
        app.kubernetes.io/name: adguard-home
        app.kubernetes.io/part-of: components
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload.kubernetes.progamesigner.dev/network
                operator: Exists
      automountServiceAccountToken: false
      containers:
      - name: adguard-home
        image: adguard-home/adguard-home:latest
        ports:
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dhcp-server
          containerPort: 67
          protocol: UDP
        - name: dhcp-client-tcp
          containerPort: 68
          protocol: TCP
        - name: dhcp-client-udp
          containerPort: 68
          protocol: UDP
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https-tcp
          containerPort: 443
          protocol: TCP
        - name: https-udp
          containerPort: 443
          protocol: UDP
        - name: dns-tls-tcp
          containerPort: 853
          protocol: TCP
        - name: dns-tls-udp
          containerPort: 853
          protocol: UDP
        - name: console
          containerPort: 3000
          protocol: TCP
        - name: dnscrypt-tcp
          containerPort: 5443
          protocol: TCP
        - name: dnscrypt-udp
          containerPort: 5443
          protocol: UDP
        - name: pprof
          containerPort: 6060
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - name: cert
          mountPath: /opt/adguardhome/cert
          readOnly: true
        - name: data
          mountPath: /opt/adguardhome/conf
          subPath: conf
        - name: data
          mountPath: /opt/adguardhome/work
          subPath: work
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: cert
        secret:
          secretName: tls-dev-progamesigner
          defaultMode: 420
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
      - name: data
        persistentVolumeClaim:
          claimName: adguard-home
