---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: adguard-home
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/part-of: components
  name: adguard-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: adguard-home
      app.kubernetes.io/name: adguard-home
      app.kubernetes.io/part-of: components
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: adguard-home
        app.kubernetes.io/name: adguard-home
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: adguard-home
        image: adguard-home/adguard-home:latest
        ports:
        - name: dns
          containerPort: 53
        - name: https
          containerPort: 443
        - name: dns-tls
          containerPort: 853
        - name: admin
          containerPort: 3000
        - name: dnscrypt
          containerPort: 5443
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: cert
          mountPath: /opt/adguardhome/cert
          readOnly: true
        - name: data
          mountPath: /opt/adguardhome/conf
          subPath: conf
        - name: data
          mountPath: /opt/adguardhome/work
          subPath: work
      serviceAccountName: default
      volumes:
      - name: data
        emptyDir: {}
      - name: cert
        secret:
          secretName: tls-dev-progamesigner
          defaultMode: 420
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
