---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: unifi-network
    app.kubernetes.io/name: unifi-network
    app.kubernetes.io/part-of: components
  name: unifi-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: unifi-network
      app.kubernetes.io/name: unifi-network
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: unifi-network
        app.kubernetes.io/name: unifi-network
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: unifi-network
        image: unifi/network:latest
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: UTC
        envFrom:
        - configMapRef:
            name: unifi-network
        ports:
        - name: snmp
          containerPort: 161
          protocol: UDP
        - name: l2-discovery
          containerPort: 1900
          protocol: UDP
        - name: stun
          containerPort: 3478
          protocol: UDP
        - name: syslog
          containerPort: 5514
          protocol: UDP
        - name: speed-test
          containerPort: 6789
          protocol: TCP
        - name: inform
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        - name: https-redirect
          containerPort: 8843
          protocol: TCP
        - name: http-redirect
          containerPort: 8880
          protocol: TCP
        - name: discovery
          containerPort: 10001
          protocol: UDP
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: data
          mountPath: /config
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: data
        emptyDir: {}
