---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: metrics-server
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metrics-server
spec:
  commonName: metrics-server
  dnsNames:
  - metrics-server.kube-system
  - metrics-server.kube-system.svc
  - metrics-server.kube-system.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: metrics-server
  privateKey:
    algorithm: RSA
    size: 2048
  secretName: metrics-server
  usages:
  - client auth
  - server auth
