---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-ip-address-pool
spec:
  addresses:
  - 192.168.32.20-192.168.32.99
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-ip-address-pool
spec:
  addresses:
  - 192.168.0.1-192.168.0.15
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: managed-ip-address-pool
spec:
  addresses:
  - 192.168.32.1-192.168.32.15
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisement
spec:
  ipAddressPools:
  - local-ip-address-pool
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: advertisement
spec:
  ipAddressPools:
  - default-ip-address-pool
  - managed-ip-address-pool
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: local
spec:
  config: |
    {
      "name": "local",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "ipam": {
            "type": "dhcp"
          }
        },
        {
          "type": "sbr"
        }
      ]
    }
