---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external-ip-address-pool
spec:
  addresses:
  - 192.168.0.11-192.168.0.15
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal-ip-address-pool
spec:
  addresses:
  - 192.168.48.11-192.168.48.15
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-ip-address-pool
spec:
  addresses:
  - 192.168.48.20-192.168.48.99
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
spec:
  ipAddressPools:
  - default-ip-address-pool
  - external-ip-address-pool
  - internal-ip-address-pool
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cluster
spec:
  config: |
    {
      "name": "vhost0",
      "type": "ptp",
      "ipam": {
        "type": "host-local",
        "subnet": "10.20.0.0/24",
        "routes": [
          {
            "dst": "10.16.0.0/14"
          }
        ]
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: local
spec:
  config: |
    {
      "name": "vlan0",
      "type": "macvlan",
      "ipam": {
        "type": "dhcp"
      }
    }
