---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: metascraper
    app.kubernetes.io/name: metascraper
    app.kubernetes.io/part-of: components
  name: metascraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: metascraper
      app.kubernetes.io/name: metascraper
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: metascraper
        app.kubernetes.io/name: metascraper
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: metascraper
        image: metascraper/metascraper:latest
        ports:
        - name: http
          containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 300m
            memory: 128Mi
      enableServiceLinks: false
      serviceAccountName: default
