---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: huginn
  files:
  - config.yaml=huginn.yaml
  - instructions.md=instructions.md
  literals:
  - HUGINN_CONFIG_FILE=/etc/huginn/config.yaml
  - HUGINN_ENVIRONMENT=prod
resources:
- controllers.yaml
secretGenerator:
- name: huginn
  envs:
  - huginn.env
  literals:
  - HUGINN_DATABASE_URL=postgresql+asyncpg://default:password@postgresql.default.svc.cluster.local:5432/huginn
  - HUGINN_REDIS_URL=redis://default:password@redis.default.svc.cluster.local:6379/0
