---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: public-ingress-nginx
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: cluster
  name: public-ingress-nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: public-ingress-nginx
      app.kubernetes.io/name: controller
      app.kubernetes.io/part-of: cluster
  template:
    metadata:
      annotations:
        prometheus.io/port: '10254'
        prometheus.io/scrape: 'true'
      labels:
        app.kubernetes.io/component: public-ingress-nginx
        app.kubernetes.io/name: controller
        app.kubernetes.io/part-of: cluster
    spec:
      automountServiceAccountToken: true
      containers:
      - name: ingress-nginx-controller
        image: ingress-nginx/controller:latest
        args:
        - /nginx-ingress-controller
        - --configmap=$(POD_NAMESPACE)/ingress-nginx-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-backend
        - --election-id=ingress-controller-leader
        - --enable-ssl-chain-completion=true
        - --ingress-class=public-ingress-nginx
        - --tcp-services-configmap=$(POD_NAMESPACE)/public-ingress-nginx-tcp
        - --udp-services-configmap=$(POD_NAMESPACE)/public-ingress-nginx-udp
        - --update-status=false
        lifecycle:
          preStop:
            exec:
              command:
              - /wait-shutdown
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: webhook
          containerPort: 8443
        - name: metrics
          containerPort: 10254
        startupProbe:
          httpGet:
            path: /healthz
            port: 10254
          initialDelaySeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
          initialDelaySeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
          initialDelaySeconds: 10
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
          runAsUser: 101
      hostNetwork: true
      priorityClassName: system-cluster-critical
      serviceAccountName: ingress-nginx-controller
      terminationGracePeriodSeconds: 300
