---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: cloudflare-warp
    app.kubernetes.io/name: proxy
    app.kubernetes.io/part-of: components
  name: cloudflare-warp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: cloudflare-warp
      app.kubernetes.io/name: proxy
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cloudflare-warp
        app.kubernetes.io/name: proxy
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: cloudflare-warp
        image: network/cloudflare-warp:latest
        ports:
        - name: socks
          containerPort: 1080
        - name: proxy
          containerPort: 8080
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 300m
            memory: 256Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            drop:
            - ALL
      enableServiceLinks: false
      serviceAccountName: default
