---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: secretariat
    app.kubernetes.io/name: gloomhaven
    app.kubernetes.io/part-of: components
  name: gloomhaven
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: secretariat
      app.kubernetes.io/name: gloomhaven
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: secretariat
        app.kubernetes.io/name: gloomhaven
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: setup
        image: gloomhaven/client:latest
        command:
        - sh
        - -c
        - |
          set -ex;
          cp -LRv /usr/share/nginx/html/. /root/.ghs/gloomhavensecretariat
          if [ -f /root/.ghs/server.json ]; then
            cp /root/.ghs/server.json /root/.ghs/gloomhavensecretariat/assets/server.json
          fi
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
        volumeMounts:
        - name: data
          mountPath: /root/.ghs
      containers:
      - name: server
        image: gloomhaven/server:latest
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 300m
            memory: 256Mi
        volumeMounts:
        - name: data
          mountPath: /root/.ghs
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gloomhaven
