---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: kube-router
  files:
  - cni-conf.json=cni-conf.json
images:
- name: kube-router/kube-router
  newName: cloudnativelabs/kube-router
  newTag: v2.1.2
resources:
- controllers.yaml
- rbac.yaml
