---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- controllers.yaml
secretGenerator:
- name: obsidian
  literals:
  - CUSTOM_USER=default
  - NO_DECOR=true
  - PASSWORD=password
  - TITLE=Obsidian
