---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: coredns
    app.kubernetes.io/name: coredns
    app.kubernetes.io/part-of: cluster
  name: coredns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: coredns
    app.kubernetes.io/name: coredns
    app.kubernetes.io/part-of: cluster
  name: system:coredns
rules:
- apiGroups:
  - ''
  resources:
  - endpoints
  - namespaces
  - pods
  - services
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: coredns
    app.kubernetes.io/name: coredns
    app.kubernetes.io/part-of: cluster
  name: system:coredns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:coredns
subjects:
- kind: ServiceAccount
  name: coredns
