---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '9153'
    prometheus.io/scrape: 'true'
  labels:
    app.kubernetes.io/component: coredns
    app.kubernetes.io/name: coredns
    app.kubernetes.io/part-of: cluster
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: CoreDNS
  name: coredns
spec:
  clusterIP: 10.16.0.8
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    app.kubernetes.io/component: coredns
    app.kubernetes.io/name: coredns
    app.kubernetes.io/part-of: cluster
