---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: services
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mariadb
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/part-of: services
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mariadb
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/part-of: services
    spec:
      automountServiceAccountToken: false
      containers:
      - name: mariadb
        image: mariadb/mariadb:latest
        envFrom:
        - secretRef:
            name: mariadb
        ports:
        - name: mariadb
          containerPort: 3306
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        resources:
          limits:
            cpu: 2000m
            memory: 8Gi
          requests:
            cpu: 500m
            memory: 1Gi
      enableServiceLinks: false
      serviceAccountName: default
      volumes:
      - name: data
        emptyDir: {}
