---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: services
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mariadb
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/part-of: services
  serviceName: headless-mariadb
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mariadb
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/part-of: services
    spec:
      automountServiceAccountToken: false
      containers:
      - name: mariadb
        image: mariadb/mariadb:latest
        envFrom:
        - secretRef:
            name: mariadb
        ports:
        - name: mariadb
          containerPort: 3306
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 8Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      enableServiceLinks: false
      serviceAccountName: default
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 24Gi
      storageClassName: ceph-rbd
