---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: syncthing-relay
    app.kubernetes.io/name: syncthing-relay
    app.kubernetes.io/part-of: services
  name: syncthing-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: syncthing-relay
      app.kubernetes.io/name: syncthing-relay
      app.kubernetes.io/part-of: services
  template:
    metadata:
      labels:
        app.kubernetes.io/component: syncthing-relay
        app.kubernetes.io/name: syncthing-relay
        app.kubernetes.io/part-of: services
    spec:
      automountServiceAccountToken: false
      containers:
      - name: syncthing-relay
        image: syncthing-relay:latest
        env:
        - name: POOLS
          value: https://relays.syncthing.net/endpoint
        - name: PROVIDED_BY
          value: 0x148 <https://0x148.com>
        - name: RATE_GLOBAL
          value: '2000000'
        ports:
        - name: discovery
          containerPort: 22026
        - name: data
          containerPort: 22067
        - name: status
          containerPort: 22070
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
          requests:
            cpu: 50m
            memory: 16Mi
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          readOnlyRootFilesystem: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      serviceAccountName: default
