---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: services
  name: redis
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.48.20
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: services
  type: LoadBalancer
