---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: metallb-excludel2
  literals:
  - |
    excludel2.yaml=
    announcedInterfacesToExclude:
    - ^cali.*
    - ^nodelocaldns.*
    - ^tunl.*
    - cbr.*
    - cni.*
    - docker.*
    - dummy.*
    - flannel.*
    - kube-ipvs.*
    - lo
    - lxcbr.*
    - veth.*
    - virbr.*
resources:
- daemonsets.yaml
- deployments.yaml
- metallb.yaml
- rbac.yaml
