---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: multus
  files:
  - cni-conf.json=cni-conf.json
  options:
    disableNameSuffixHash: true
resources:
- controllers.yaml
- rbac.yaml
