---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: multus
  files:
  - cni-conf.json=cni-conf.json
images:
- name: multus/multus
  newName: ghcr.io/k8snetworkplumbingwg/multus-cni
  newTag: v4.1.3
resources:
- crds/network-attachment-definitions.yaml

- controllers.yaml
- rbac.yaml
