---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: firecrawl
    app.kubernetes.io/part-of: components
  name: firecrawl-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/name: firecrawl
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/name: firecrawl
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: firecrawl
        image: firecrawl/api:latest
        imagePullPolicy: Always
        env:
        - name: FLY_PROCESS_GROUP
          value: app
        - name: HOST
          value: 0.0.0.0
        - name: PORT
          value: '3002'
        envFrom:
        - configMapRef:
            name: firecrawl
        - secretRef:
            name: firecrawl
        ports:
        - name: http
          containerPort: 3002
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /v0/health/liveness
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /v0/health/readiness
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 128Mi
      enableServiceLinks: false
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/name: firecrawl
    app.kubernetes.io/part-of: components
  name: firecrawl-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/name: firecrawl
      app.kubernetes.io/part-of: components
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
        app.kubernetes.io/name: firecrawl
        app.kubernetes.io/part-of: components
    spec:
      automountServiceAccountToken: false
      containers:
      - name: firecrawl
        image: firecrawl/worker:latest
        imagePullPolicy: Always
        env:
        - name: FLY_PROCESS_GROUP
          value: worker
        envFrom:
        - configMapRef:
            name: firecrawl
        - secretRef:
            name: firecrawl
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 128Mi
      enableServiceLinks: false
      serviceAccountName: default
