---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: firecrawl
  literals:
  - NUM_WORKERS_PER_QUEUE=4
  - PLAYWRIGHT_MICROSERVICE_URL=http://windmill.default.svc.cluster.local:8000/api/r/default/firecrawl/scrape
  - REDIS_RATE_LIMIT_URL=redis://redis.default.svc.cluster.local:6379
  - REDIS_URL=redis://redis.default.svc.cluster.local:6379
  - SELF_HOSTED_WEBHOOK_URL=
  - USE_DB_AUTHENTICATION=false
resources:
- controllers.yaml
secretGenerator:
- name: firecrawl
  literals:
  - BULL_AUTH_KEY=default
