---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: metrics-server/metrics-server
  newName: registry.k8s.io/metrics-server/metrics-server
  newTag: v0.7.2
resources:
- controllers.yaml
- policies.yaml
- rbac.yaml
