---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: metrics-server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics-server
      app.kubernetes.io/name: metrics-server
      app.kubernetes.io/part-of: kubernetes
