name: Auto Approve PRs and Merge

on:
  pull_request:
    types:
    - opened
    branches:
    - workflows/kustomize/rsshub-v*

jobs:
  approve-and-merge:
    name: Approve and Merge PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Approve and Merge PR
      run: |
        gh pr merge ${{ github.event.pull_request.number }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
