name: Trigger Deployment Webhook

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tailscale/github-action@v3
      with:
        authkey: ${{ secrets.TS_AUTH_KEY }}
        statedir: /tmp/tailscale-state
        use-cache: 'true'
    - name: Trigger
      run: |
        curl -sSL -X POST -H 'Authorization: Bearer ${{ secrets.DEPLOY_API_KEY }}' ${{ secrets.DEPLOY_API_URL }}

